dist: focal
os: linux
language: node_js
node_js:
 - 16
addons:
 chrome: stable
 sonarcloud:
  organization: tuanicom-github
services:
  - xvfb
before_script:
 - npm install -g @angular/cli
script: bash rebuild.sh
cache: npm
notifications:
 webhooks: "https://coveralls.io/webhook"
