dist: trusty
os: linux
language: node_js
node_js:
    - 'lts/*'
addons:
    sonarcloud:
        organization: tuanicom-github
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get clean -q
    - sudo apt-get update -q
    - sudo apt-get install dpkg -y
    - sudo apt-get -y install google-chrome-stable --allow-unauthenticated
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
before_script:
    - 'npm install -g @angular/cli'
script:
    - 'cd frontend'
    - 'npm ci'
    - 'npm install coveralls'
    - 'ng build --prod'
    - 'ng test --watch false --browsers ChromeHeadless --code-coverage'
    - 'npm run pree2e'
    - 'ng e2e --prod'
    - 'ng lint'
    - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
    - 'cd ../backend'
    - 'npm ci'
    - 'npm install coveralls'
    - 'npm run grunt ts'
    - 'npm test'
    - 'npm run grunt tslint'
    - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
    - 'sonar-scanner'
cache: npm
notifications:
  webhooks: https://coveralls.io/webhook
