sudo: required
dist: trusty
language: node_js
node_js:
    - '8.12'
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
    sonarcloud:
        organization: tuanicom-github
before_install:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
before_script:
    - 'npm install -g @angular/cli'
script:
    - 'cd frontend'
    - 'npm install'
    - 'ng build'
    - 'ng test --watch false --browsers ChromeHeadless --code-coverage'
    - 'npm run coverall'
    - 'ng e2e'
    - 'ng lint'
    - 'cd ..'
    - 'sonar-scanner'
cache:
    directories:
        - node_modules
