version: 1.0.{build}
image: Visual Studio 2019
environment: 
  nodejs_version: Current   
  matrix:
    - nodejs_version: Current
install:
- ps: Install-Product node $env:nodejs_version
- npm install codecov -g
- npm install -g snyk
- npm install -g @angular/cli
- if not exist C:\projects\incap\frontend\node_modules\protractor\node_modules\webdriver-manager\selenium ( mkdir C:\projects\incap\frontend\node_modules\protractor\node_modules\webdriver-manager\selenium )
- curl -oC:\projects\incap\frontend\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
- choco upgrade GoogleChrome -y --ignore-checksums
cache: 
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - frontend\node_modules -> package.json                               # local npm modules
  # scripts to run before build
before_build:
- cd frontend
- npm ci
- cd ..
- cd backend
- npm ci
- cd ..
build_script:
- cd frontend
- ng build --prod 
- cd ..
- cd backend
- npm run grunt ts
- cd ..
test_script:
- cd frontend
- ng test --watch false --browsers ChromeHeadless --code-coverage
- appveyor-retry npm run pree2e
- npm run pree2e
- ng e2e --no-webdriver-update --prod
- codecov --disable=gcov
- cd ..
- cd backend
- npm test
- codecov --disable=gcov
- cd ..
after_test:
- cd frontend
- npx ng lint frontend
- snyk monitor --file=package.json --project-name=incap-frontend
- cd ..
- cd backend
- npm run grunt eslint
- snyk monitor --file=package.json --project-name=incap-backend
- cd ..
artifacts:
- path: frontend/coverage/index.html
  name: Frontend Coverage
- path: backend/coverage/lcov-report/index.html
  name: Frontend Coverage