version: 1.0.{build}
image: Visual Studio 2017
install:
- npm install -g @angular/cli
- mkdir C:\projects\incap\frontend\node_modules\protractor\node_modules\webdriver-manager\selenium
- curl -oC:\projects\incap\frontend\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
cache: 
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - frontend\node_modules -> package.json                               # local npm modules
build_script:
- cd frontend
- npm install
- ng build
test_script:
- ng test --watch false --browsers ChromeHeadless --code-coverage
- appveyor-retry npm run pree2e
- npm run pree2e
- ng e2e --no-webdriver-update
- ng lint
artifacts:
- path: frontend/coverage/index.html
  name: Coverage