version: 1.0.{build}
image: Visual Studio 2019
environment: 
  nodejs_version: Current   
  matrix:
    - nodejs_version: Current
install:
- ps: Install-Product node $env:nodejs_version
- npm install codecov -g
- npm install -g snyk
- npm install -g @angular/cli
cache: 
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - frontend\node_modules -> package.json                               # local npm modules
  # scripts to run before build
before_build:
- cd frontend
- npm ci
- cd ..
- cd backend
- npm ci
- cd ..
build_script:
- cd frontend
- ng build --configuration production 
- cd ..
- cd backend
- npm run grunt ts
- cd ..
test_script:
- cd frontend
- ng test --watch false --browsers ChromeHeadless --code-coverage
- codecov --disable=gcov
- cd ..
- cd backend
- npm test
- codecov --disable=gcov
- cd ..
after_test:
- cd frontend
- npx ng lint frontend --format html --output-file=eslint.html
- cd ..
- cd backend
- npm run grunt eslint -- --format=html --output-file=eslint.html
- cd ..
artifacts:
- path: frontend/coverage/index.html
  name: Frontend Coverage
- path: backend/coverage/lcov-report/index.html
  name: Backend Coverage
- path: frontend/eslint.html
  name: Frontend Linting
- path: backend/eslint.html
  name: Backend Linting