version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: npm install -g angular-cli
cache: node_modules
build_script:
- cd frontend
- npm install
- ng build
test_script:
- ng test --watch false --browsers ChromeHeadless --code-coverage
- ng e2e
artifacts:
- path: coverage/index.html
  name: Coverage