services:
  frontend:
    image: tuanicom/incap-frontend:latest
    pull_policy: always
    restart: unless-stopped

  backend:
    image: tuanicom/incap-backend:latest
    pull_policy: always
    restart: unless-stopped

