version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "8080:8080" # specify port forewarding
    environment:
      CATEGORIES_API_URL: http://backend:4000/categories
    depends_on:
      - backend

  backend: #name of the second service
    build: backend # specify the directory of the Dockerfile
    environment:
      MONGO_DB_URL: mongodb:27017
    depends_on:
      - mongodb

  mongodb: # name of the third service
    image: mongo # specify image to build container from
