version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of the first service
    build: apps/frontend # specify the directory of the Dockerfile with Nx-based build

  backend: #name of the second service
    build: apps/backend # specify the directory of the Dockerfile with Nx-based build

  mongodb: # name of the third service
    image: mongo:8.0.20 # specify image to build container from
