version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of the first service
    build: frontend # specify the directory of the Dockerfile

  backend: #name of the second service
    build: backend # specify the directory of the Dockerfile

  mongodb: # name of the third service
    image: mongo # specify image to build container from
