require:
  - 'ts-node/register'
  - 'source-map-support/register'
full-trace: true
bail: true
timeout: 10000
spec:
  - 'articles/*.spec.ts'
  - 'categories/*.spec.ts'
  - 'users/*.spec.ts'
reporter: mocha-junit-reporter
reporter-option:
  - mochaFile=./tests-results/tests-results.xml
