apiVersion: v1
kind: Service
metadata:
  name: incap-backend
spec:
  type: NodePort
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
    nodePort: 30400
  selector:
    app: incap-backend
status:
  loadBalancer: {}
