apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: incap-backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: incap-backend
    spec:
      containers:
      - env:
        - name: MONGO_DB_URL
          value: mongodb:27017
      - image: tuanicom/incap-backend
        name: incap-backend
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
status: {}
