apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: incap-backend
  name: incap-backend
spec:
  type: NodePort
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
    nodePort: 30400
  selector:
    io.kompose.service: incap-backend
status:
  loadBalancer: {}
