version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of the first service
    image: tuanicom/incap-frontend
    ports:
      - "80:8080" # specify port forewarding
    environment:
      CATEGORIES_API_URL: http://localhost:4000
    depends_on:
      - backend

  backend: #name of the second service
    image: tuanicom/incap-backend
    ports:
      - "4000:4000" #specify ports forewarding
    environment:
      MONGO_DB_URL: mongodb:27017
    links:
      - mongodb

  mongodb: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
