apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    name: incap-frontend
    io.kompose.service: incap-frontend
  name: incap-frontend
  namespace: incap
spec:
  type: LoadBalancer
  ports:
  - name: "incap-frontend"
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    io.kompose.service: incap-frontend
status:
  loadBalancer: {}
