apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: incap-frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels: 
        app: incap-frontend
    spec:
      containers:
      - image: tuanicom/incap-frontend
        name: incap-frontend
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
