apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: mongodb
  name: mongodb
  namespace: incap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - image: mongo:8.0.20
          imagePullPolicy: IfNotPresent
          name: mongodb
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-tmp
              mountPath: /tmp
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
      volumes:
        - name: mongodb-data
          emptyDir: {}
        - name: mongodb-tmp
          emptyDir: {}
